doc_dict = {
    '0.1': 'Carta d\'identita\'',
    '0.2': 'Carta d\'identita\'',
    '0.3': 'Carta d\'identita\'',
    '0.5': 'Carta d\'identita\'',
    '0.6': 'Modello 730',
    '1.1': 'Estratto conto',
    '1.2': 'Estratto conto',
    '1.4': 'Istruzione e Impiego',
    '1.5': 'Estratto conto',
    '1.6.1': 'Estratto conto',
    '1.6.2': 'Estratto conto',
    '1.6.3': 'Estratto conto',
    '1.6.4': 'Estratto conto',
    '1.6.5': 'Estratto conto',
    '1.6.7': 'Estratto conto',
    '1.6.8': 'Estratto conto',
    '1.6.9': 'Estratto conto',
    '1.7.1': 'Estratto conto',
    '1.7.2': 'Estratto conto',
    '1.7.3': 'Estratto conto',
    '1.7.4': 'Estratto conto',
    '1.7.5': 'Estratto conto',
    '1.7.6': 'Estratto conto',
    '1.8': 'Estratto conto',
    '2.1': 'Estratto conto',
    '2.2': 'Estratto conto',
    '2.3': 'Estratto conto',
    '2.4': 'Estratto conto',
    '2.5': 'Estratto conto',
    '2.6': 'Estratto conto',
    '2.7': 'Estratto conto',
    '2.8': 'Estratto conto',
    '2.9': 'Estratto conto',
    '2.10': 'Modello 730',
}

print(doc_dict['1.1'])